### PR TITLE
Fix links in Readme

### PR DESCRIPTION
**Pull request by padde**

### CODE REVIEW

**Comment by fidian** [comment]
The syntax for links in markdown is

```
[text to display](url for link)
```

This is even shown in GitHub's Markdown documentation: https://guides.github.com/features/mastering-markdown/

**Comment by padde** [comment]
Yes and no. For links with an inline URL, the syntax is

```
[link text](http://www.example.com)
```

For links with references, the syntax is

```
[link text][reference]

...

[reference]: http://www.example.com
```

http://daringfireball.net/projects/markdown/syntax#link

Try clicking on the links in the Readme on master vs. this branch and you'll see why I patched them :wink:.

**Comment by fidian** [comment]
You're totally right.  When comparing the documents, I looked at my master branch and your master branch and didn't see any difference in the links.  I switched to look at the right branch of yours plus I tried clicking on the links.

Thanks yet again for the help!

**Comment by padde** [comment]
No problem. Thanks for creating the plugin :wink:

**Pull request merged**
